### ISSUE TITLE
大佬有空时能帮忙编译个kernelsu的boot嘛

### ISSUE THREAD

**Issue by liangjaden** [jacid233/android_kernel_oplus_sm8250#2]
想玩下kernelsu，但没编译基础及环境，找了半天才找到这居然有这机子的内核源码，很是激动哈哈。
这是kernelsu的官链，https://kernelsu.org/zh_CN/guide/unofficially-support-devices.html。
就顺口提一嘴，看缘分哈哈。

**Comment by liangjaden** [comment]
对不起，是我眼瞎了，才发现你有构建了kernelsu的boot，非常感谢~~

**Comment by liangjaden** [comment]
呃，你打包的kernelsu内核是要通过twrp方式刷入的嘛？我看指引里说可以用findx2的twrp，但我找不到相关资源，可以提供下链接嘛，谢谢

**Comment by jacid233** [comment]
> 呃，你打包的kernelsu内核是要通过twrp方式刷入的嘛？我看指引里说可以用findx2的twrp，但我找不到相关资源，可以提供下链接嘛，谢谢
ColorOS7.1: https://wwfg.lanzoum.com/i8fh90kt6jch
ColorOS12.1: https://wwfg.lanzoum.com/iqLv10tzdqze
ColorOS13.0/1:https://wwfg.lanzoum.com/iW1Xs0tzdeda

**Comment by liangjaden** [comment]
收到~非常感谢~~
